### ISSUE TITLE
Can you make a Flask version?

### ISSUE THREAD

**Issue by Keiku** [Nneji123/Serving-FastAPI-Application-with-AWS-and-Pyngrok#2]
I want to create a web application using AWS EC2 + Flask + ngrok, but I'm not a web application engineer, so I'm currently studying. I would appreciate it if you could also create a version of Flask if possible. Thank you.

**Comment by Nneji123** [comment]
Hello, sorry but I can't help with that because I no longer have access to
AWS. Unless I'm paid to help I can't.

**Comment by Keiku** [comment]
Thank you for your comment.
